version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codegym
      MYSQL_DATABASE: ticinema
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network
  backend:
    build: ./ticinema_server
    container_name: backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - springboot-network
  frontend:
    build: ./ticinema_client
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - springboot-network
volumes:
  mysql_data:
networks:
  springboot-network: